# Site settings

# Dependencies
markdown:         kramdown
highlighter:      pygments

kramdown:
  input: GFM


# Permalinks
permalink:        pretty
-- relative_permalinks: true


# Setup
title:            "DioT Labs and Guides"
tagline:          'CMU Mini 3 - Spring 2016'

email: 			daragh@daraghbyrne.me

description:     "A series of guides, tutorials and labs to accompany CMU's <a href='http://daraghbyrne.github.io/diot2016/'>DIoT Spring 2016 course</a>; a hands-on introductory course exploring the Internet of Things and connected product experiences."
-- url:              http://diotlabs.daraghbyrne.me
-- baseurl:          /diotlabs
baseurl:          "http://diotlabs.daraghbyrne.me"

author:
  name:           'Daragh Byrne'
  email: 		  daragh@daraghbyrne.me
  url:            http://daraghbyrne.github.io/diotlabs/

email: 			  daragh@daraghbyrne.me
twitter_username: diotlabs
github_username:  daraghbyrne

paginate:         5

# Custom vars
version:          1.0.0

github:
  user:           daraghbyrne
  repo:           https://github.com/daraghbyrne/diotlabs
  
github_source_code: https://github.com/daraghbyrne/DesigningIoT
  
  
  
# The left menu bar
menu:
    items:
      - text: "Introduction"
        relativeUrl: /
      - text: "Getting Started"
        relativeUrl: /getting-started/
        items:
          - text: "What is the Particle Platform"
            relativeUrl: /getting-started/the-particle-platform
          - text: "Understanding your Photon"
            relativeUrl: /getting-started/understanding-your-photon
          - text: "Setting up your Photon"
            relativeUrl: /getting-started/setting-up-your-photon
          - text: "The Particle Community"
            relativeUrl: /getting-started/the-particle-community

      - text: "1. A Simple Internet Appliance"
        relativeUrl: /1-a-simple-internet-appliance/
        items:
          - text: "Learn: Understanding Breadboards"
            relativeUrl: /1-a-simple-internet-appliance/breadboards
          - text: "Learn: Understanding Jumper Wires"
            relativeUrl: /1-a-simple-internet-appliance/jumpers
          - text: "Learn: Understanding Resistors"
            relativeUrl: /1-a-simple-internet-appliance/resistors
          - text: "Learn: Understanding LEDs"
            relativeUrl: /1-a-simple-internet-appliance/leds
          - text: "Tutorial: First Sketch - A blinking LED"
            relativeUrl: /1-a-simple-internet-appliance/first-sketch
          - text: "Guide: Writing Functions"
            relativeUrl: /1-a-simple-internet-appliance/writing-functions
          - text: "Guide: Making Functions available through the Particle Cloud"
            relativeUrl: /1-a-simple-internet-appliance/making-functions-available
          - text: "Tutorial: Connecting your LED to the Internet"
            relativeUrl: /1-a-simple-internet-appliance/iot-led			
      - text: "2. LEDs Continued"
        relativeUrl: /2-leds-continued/
        items:
          - text: "Guide: Controlling and Fading LEDs: Pulse Width Modulation"
            relativeUrl: /2-leds-continued/pwm
          - text: "Guide: analogWrite"
            relativeUrl: /2-leds-continued/analogwrite
          - text: "Tutorial: A Connected Dimmer Switch"
            relativeUrl: /2-leds-continued/dimmer
          - text: "Guide: RGB LEDs"
            relativeUrl: /2-leds-continued/rgb-leds
          - text: "Tutorial: Using an RGB LED"
            relativeUrl: /2-leds-continued/using-rgb-leds
          - text: "Guide: Libraries - Adding Functionality"
            relativeUrl: /2-leds-continued/libraries
          - text: "Tutorial: Using the in-built RGB LED"
            relativeUrl: /2-leds-continued/built-in-rgbled
      - text: "3. Working with Sensors"
        relativeUrl: /3-working-with-sensors/
        items:
          - text: "Guide: What are sensors?"
            relativeUrl: /3-working-with-sensors/sensors
          - text: "Guide: Reading from Sensors: Using analogRead"
            relativeUrl: /3-working-with-sensors/analogread			
          - text: "Guide: Resistive Sensors and Pull Down Resistors"
            relativeUrl: /3-working-with-sensors/pull-down-resistors	
          - text: "Guide: Particle Cloud and Variables"
            relativeUrl: /3-working-with-sensors/cloud-variables
          - text: "Guide: Working with Sensor Data: map()"
            relativeUrl: /3-working-with-sensors/map
          - text: "Tutorial: Using a photoresistor"
            relativeUrl: /3-working-with-sensors/photoresistors
          - text: "Tutorial: Using a DS18B20 Temperature Sensor"
            relativeUrl: /3-working-with-sensors/DS18B20
          - text: "Tutorial: Using a TMP36 Temperature Sensor"
            relativeUrl: /3-working-with-sensors/tmp36
          - text: "Tutorial: Using a FSR"
            relativeUrl: /3-working-with-sensors/fsrs
      - text: "4. Basic Skills"
        relativeUrl: /4-basic-skills/
        items:
          - text: "Tutorial: Soldering"
            relativeUrl: /4-basic-skills/solder-it
      - text: "5. Getting Inputs"
        relativeUrl: /5-getting-input/
        items:
          - text: "Guide: Inputs: Making Physical Interfaces"
            relativeUrl: /5-getting-input/inputs
          - text: "Tutorial: Using a pushbutton"
            relativeUrl: /5-getting-input/buttons
          - text: "Tutorial: Using a switch"
            relativeUrl: /5-getting-input/switches
          - text: "Tutorial: Using a potentiometer"
            relativeUrl: /5-getting-input/rotpots
      - text: "6. Controlling Outputs"
        relativeUrl: /6-controlling-outputs
        items:
          - text: "Guide: Movement and Motors"
            relativeUrl: /6-controlling-outputs/motors
          - text: "Tutorial: Using a Servo"
            relativeUrl: /6-controlling-outputs/servo
          - text: "Tutorial: Making sounds with Piezos"
            relativeUrl: /6-controlling-outputs/piezo
      - text: "7. Communicating through Events"
        relativeUrl: /7-communicating-events
        items:
          - text: "Guide: Particle Cloud & Publishing Events"
            relativeUrl: /7-communicating-events/publishing-events
          - text: "Tutorial: A PIR and Particle.publish()"
            relativeUrl: /7-communicating-events/pir
          - text: "Tutorial: Events between devices - creating a connected doorbell"
            relativeUrl: /7-communicating-events/doorbell
      - text: "8. Connecting to Services with IFTTT"
        relativeUrl: /8-ifttt
      - text: "Tips and Troubleshooting"
        relativeUrl: /tips-and-troubleshooting/
      - text: "Resources"
        relativeUrl: /resources/
      - text: "FAQ"
        relativeUrl: /faq/
      - text: "DIoT 2016"
        absoluteUrl: http://daraghbyrne.github.io/diot2016


